bin/roseus: try to find irteusg, if irteusgl is not found

diff --git a/roseus/bin/roseus.in b/roseus/bin/roseus.in
--- a/roseus/bin/roseus.in
+++ b/roseus/bin/roseus.in
@@ -4,8 +4,14 @@ set -e
 if [ "@APPLE@" = "1" ]; then
   EUSLISP_EXE=/usr/local/bin/irteusgl  # osx
 else
-  EUSLISP_EXE=`find -L $EUSDIR -type f -name irteusgl`  # linux
+  # https://serverfault.com/questions/225798/can-i-make-find-return-non-0-when-no-matching-files-are-found
+  EUSLISP_EXE=`find -L $EUSDIR/$ARCHDIR -type f -name irteusgl -exec false {} + -print && \
+               find -L $EUSDIR/$ARCHDIR -type f -name irteusg  -exec false {} + -print && \
+               find -L $EUSDIR -type f -name irteusgl -exec false {} + -print && \
+               find -L $EUSDIR -type f -name irteusg  -exec false {} + -print    \
+               ` || true # linux
 fi
+if [ ! -e "$EUSLISP_EXE" ]; then echo "Could not found irteusgl program, please install/compile jskeus"; exit 1; fi
 ROSEUS_DIR=`rospack find roseus`
 ARG_STR=("(pushnew \"${ROSEUS_DIR}/euslisp/\" *load-path* :test #'equal)" \
         ${ROSEUS_DIR}/euslisp/roseus.l ${ROSEUS_DIR}/euslisp/eustf.l ${ROSEUS_DIR}/euslisp/actionlib.l ${ROSEUS_DIR}/euslisp/roseus-utils.l)
